Models/AcervoModel.cs
using System.ComponentModel.DataAnnotations;

namespace acervoLivros.Models
{
    public class AcervoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o titulo do livro")]
        public string? Title { get; set; }


        [Required(ErrorMessage = "Digite uma descrição do livro")]
        public string? Description { get; set; }


        [Required(ErrorMessage = "Digite o valor do livro")]
        public double? Price { get; set; }

        public DateTime Updating { get; set; } = DateTime.Now;
    }
}

Models/ErrorViewModel.cs
namespace acervoLivros.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AcervoController.cs
using acervoLivros.Data;
using acervoLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace acervoLivros.Controllers
{
    public class AcervoController : Controller
    {
        private readonly AppDbContext _db;
        public AcervoController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<AcervoModel> livros = _db.Livros;
            return View(livros);
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            AcervoModel livro = _db.Livros.FirstOrDefault(x => x.Id == id);

            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            AcervoModel livro = _db.Livros.FirstOrDefault(x => x.Id == id);

            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }


        [HttpPost]
        public IActionResult Register(AcervoModel livros)
        {
            if (ModelState.IsValid)
            {
                _db.Livros.Add(livros);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public IActionResult Edit(AcervoModel livro)
        {
            if (ModelState.IsValid)
            {
                _db.Livros.Update(livro);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(livro);
        }

        [HttpPost]
        public IActionResult Delete(AcervoModel livro)
        {
            if (livro == null)
            {
                return NotFound();
            }

            _db.Livros.Remove(livro);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using acervoLivros.Models;

namespace acervoLivros.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Acervo/Delete.cshtml
@model AcervoModel
@{
    ViewData["Title"] = "Excluir Livro";
}

<div class="container p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1>Excluir Livro</h1>
    </div>

    <form method="post" asp-controller="Acervo" asp-action="Delete">

        <input type="hidden" asp-for="Id">

        <h2>Deseja realmente excluir o livro?</h2>

        <div class="mb-3">
            <label for="Title" class="form-label">Titulo:</label>
            <input asp-for="Title" type="text" class="form-control" id="Title" placeholder="Digite o nome do livro"
                disabled>
            <span style="color: red;" asp-validation-for="Title"></span>
        </div>

        <div class="mb-3">
            <label for="Description" class="form-label">Descrição:</label>
            <input asp-for="Description" type="text" class="form-control" id="Description"
                placeholder="Digite uma descrição sobre o livro" disabled>
            <span style="color: red;" asp-validation-for="Description"></span>
        </div>

        <div class="mb-3">
            <label for="Price" class="form-label">Preço:</label>
            <input asp-for="Price" type="text" class="form-control" id="Price" placeholder="Digite o valor do livro"
                disabled>
            <span style="color: red;" asp-validation-for="@Model.Price"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Acervo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Acervo/Edit.cshtml
@model AcervoModel
@{
    ViewData["title"] = "Editar Livro";
}

<div class="container p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1>Edição Livro</h1>
    </div>

    <form method="post" asp-controller="Acervo" asp-action="Edit">

        <input type="hidden" asp-for="Id">

        <div class="mb-3">
            <label for="Title" class="form-label">Titulo:</label>
            <input asp-for="Title" type="text" class="form-control" id="Title" placeholder="Digite o nome do livro">
            <span style="color: red;" asp-validation-for="Title"></span>
        </div>

        <div class="mb-3">
            <label for="Description" class="form-label">Descrição:</label>
            <input asp-for="Description" type="text" class="form-control" id="Description"
                placeholder="Digite uma descrição sobre o livro">
            <span style="color: red;" asp-validation-for="Description"></span>
        </div>

        <div class="mb-3">
            <label for="Price" class="form-label">Preço:</label>
            <input asp-for="Price" type="text" class="form-control" id="Price" placeholder="Digite o valor do livro">
            <span style="color: red;" asp-validation-for="@Model.Price"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Acervo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Acervo/Index.cshtml
@model IEnumerable<AcervoModel>

<div class="container">

    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Livros Cadastrados</h1>
        <a class="btn btn-success mx-2" asp-controller="Acervo" asp-action="Register">Cadastrar Novo Livro</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Titulo</th>
                <th scope="col">Descrição</th>
                <th scope="col">Preço</th>
                <th scope="col">Última Edição</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                @foreach (var livro in Model)
                {
                    <tr>
                        <th scope="row">@livro.Title</th>
                        <td>@livro.Description</td>
                        <td>R$: @livro.Price</td>
                        <td>@livro.Updating</td>
                        <td>
                            <a asp-route-id="@livro.Id" asp-controller="Acervo" asp-action="Edit" class="btn btn-warning mx-2">Editar</a>
                            <a asp-route-id="@livro.Id" asp-controller="Acervo" asp-action="Delete" class="btn btn-danger mx-2">Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Acervo/Register.cshtml
@model AcervoModel
@{
    ViewData["Title"] = "Cadastrar Livro";
}

<div class="container p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1>Cadastrar Livro</h1>
    </div>

    <form method="post" asp-controller="Acervo" asp-action="Register">
        <div class="mb-3">
            <label for="Title" class="form-label">Titulo:</label>
            <input asp-for="Title" type="text" class="form-control" id="Title" placeholder="Digite o nome do livro">
            <span style="color: red;" asp-validation-for="Title"></span>
        </div>

        <div class="mb-3">
            <label for="Description" class="form-label">Descrição:</label>
            <input asp-for="Description" type="text" class="form-control" id="Description"
                placeholder="Digite uma descrição sobre o livro">
            <span style="color: red;" asp-validation-for="Description"></span>
        </div>

        <div class="mb-3">
            <label for="Price" class="form-label">Preço:</label>
            <input asp-for="Price" type="text" class="form-control" id="Price" placeholder="Digite o valor do livro">
            <span style="color: red;" asp-validation-for="@Model.Price"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
            <a class="btn btn-primary w-50" asp-controller="Acervo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - acervoLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/acervoLivros.styles.css" asp-append-version="true" />
</head>

<body style="overflow: hidden;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Acervo Livros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acervo"
                                asp-action="Index">Acervo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>